<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Theme\Module'                        => __DIR__ . '/Module.php',
    'Theme\Controller\IndexController' => __DIR__ . '/src/Theme/Controller/IndexController.php',
    'ThemeTest\Framework\TestCase'        => __DIR__ . '/tests/Theme/Framework/TestCase.php',
    'ThemeTest\SampleTest'                => __DIR__ . '/tests/Theme/SampleTest.php',
);
